'\" t
.\"     Title: git-multpush
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/08/2010
.\"    Manual: \ \&
.\"    Source: \ \& 1.0
.\"  Language: English
.\"
.TH "GIT\-MULTPUSH" "1" "02/08/2010" "\ \& 1\&.0" "\ \&"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-multipush \- push a branch to multiple remotes in one command\&.
.SH "SYNOPSIS"
.sp
\fBgit multipush\fR [\fB\-v\fR] [\fB\-e\fR] [\fB\-n\fR] [\fB\-b\fR \fI<branch>\fR] [\fI<remote>\&...\fR] [\-\- \fIGIT_OPTIONS\fR]
.SH "DESCRIPTION"
.sp
Particularly useful for people hosting on multiple git repo providers all at once\&. e\&.g\&., github\&.com, gitorious\&.org and repo\&.or\&.cz\&.
.SH "OPTIONS"
.PP
\fB\-v\fR
.RS 4
Print the git commands before executing them\&.
.RE
.PP
\fB\-e\fR
.RS 4
Fail immediately when any push fails\&. Otherwise, we fail after all pushes with the error code of the last failed push\&.
.RE
.PP
\fB\-n\fR
.RS 4
Don\(cqt run any of the git commands\&. Only print them, as in
\fB\-v\fR\&.
.RE
.PP
\fB\-b\fR
.RS 4
The branch to push \(em defaults to
git symbolic\-ref HEAD\&.
.RE
.PP
<branch>
.RS 4
Any branch name that
\fBgit push\fR
can handle\&.
.RE
.PP
<remote>\&.\&.\&.
.RS 4
The list of remotes to push to \(em defaults to origin\&.
.RE
.PP
\fIGIT_OPTIONS\fR
.RS 4
Options passed directly on to
\fBgit push\fR\&.
.RE
.SH "EXIT STATUS"
.sp
0 on success and non\-zero on failure\&.
.SH "AUTHOR"
.sp
Gavin Beatty <gavinbeatty@gmail\&.com>
.SH "RESOURCES"
.sp
Website: http://code\&.google\&.com/p/git\-multipush/
.SH "REPORTING BUGS"
.sp
Please report all bugs and wishes to <gavinbeatty@gmail\&.com>
.SH "COPYING"
.sp
git\-multipush Copyright (C) 2010 Gavin Beatty, <gavinbeatty@gmail\&.com>
.sp
Free use of this software is granted under the terms of the GNU General Public License version 3, or at your option, any later version\&. (GPLv3+)
