'\" t
.\"     Title: git-multpush
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/17/2010
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "GIT\-MULTPUSH" "1" "02/17/2010" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-multipush \- push a branch to multiple remotes in one command\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgit multipush\fR [\fIOPTIONS\fR] [\fI<remote>\&...\fR] [\-\- \fIGIT_OPTIONS\fR]
\fBgit multipush\fR [\fIOPTIONS\fR] \fB\-s\fR \fI<remote>\fR [\&...]
\fBgit multipush\fR [\fIOPTIONS\fR] \fB\-\-unset\fR
\fBgit multipush\fR [\fIOPTIONS\fR] \fB\-g\fR
.fi
.SH "DESCRIPTION"
.sp
Particularly useful for people hosting on multiple git repo providers all at once\&. e\&.g\&., github\&.com, gitorious\&.org and repo\&.or\&.cz\&.
.SH "OPTIONS"
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Print the git commands before executing them\&.
.RE
.PP
\fB\-e, \-\-error\fR
.RS 4
Fail immediately when any push fails\&. Otherwise, we fail after all pushes with the error code of the last failed push\&.
.RE
.PP
\fB\-n, \-\-dry\-run\fR
.RS 4
Don\(cqt run any of the git commands\&. Only print them, as in
\fB\-v\fR\&.
.RE
.PP
\fB\-b, \-\-branch\fR=\fI<branch>\fR
.RS 4
The branch to push\&. If none given, none are passed on to
\fBgit push\fR\&. If
\fI<branch>\fR
is given with no
\fI<remote>\'s and no \'multipush\&.remotes\fR
set, origin is used as the
\fI<remote>\fR\&.
.RE
.PP
\fB\-s, \-\-set\fR
.RS 4
Set
\fImultipush\&.remotes\fR
to a comma\-separated list of the given
\fI<remotes>\fR\&. They will be used as the list of remotes to push to when none are passed explicitely\&.
.RE
.PP
\fB\-\-unset\fR
.RS 4
Unset
\fImultipush\&.remotes\fR\&.
.RE
.PP
\fB\-g, \-\-get\fR
.RS 4
Get
\fImultipush\&.remotes\fR\&.
.RE
.PP
\fB\-\-system\fR
.RS 4
Passed directly on to
\fIgit config\fR\&.
.RE
.PP
\fB\-\-global\fR
.RS 4
Passed directly on to
\fIgit config\fR\&.
.RE
.PP
\fB\-\-file\fR=\fI<file>\fR
.RS 4
Passed directly on to
\fIgit config\fR\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version info in the format
git multipush version $version\&.
.RE
.PP
<remote>\&.\&.\&.
.RS 4
The list of remotes to push to\&. None passed to
\fBgit push\fR
if none given\&.
.RE
.PP
\fIGIT_OPTIONS\fR
.RS 4
Options passed directly on to
\fBgit push\fR\&.
.RE
.SH "EXIT STATUS"
.sp
0 on success and non\-zero on failure\&.
.SH "AUTHOR"
.sp
Gavin Beatty <gavinbeatty@gmail\&.com>
.SH "RESOURCES"
.sp
Website: http://code\&.google\&.com/p/git\-multipush/
.SH "REPORTING BUGS"
.sp
Please report all bugs and wishes to <gavinbeatty@gmail\&.com>
.SH "COPYING"
.sp
git\-multipush Copyright (C) 2010 Gavin Beatty, <gavinbeatty@gmail\&.com>
.sp
Free use of this software is granted under the terms of the GNU General Public License version 3, or at your option, any later version\&. (GPLv3+)
